services:
  - type: web
    name: Recruitment-Crawling
    env: node
    buildCommand: yarn install
    startCommand: yarn start
    envVars:
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: 'true'  # Puppeteer에서 기본적으로 Chromium을 다운로드하지 않도록 설정
    build:
      packages:
        - gconf-service
        - libasound2
        - libatk1.0-0
        - libcups2
        - libdbus-1-3
        - libgtk-3-0
        - libnspr4
        - libnss3
        - libxss1
        - lsb-release
        - xdg-utils
        - wget
